---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/6021649cc1f247001630fead/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Site Configuration
  templates:
  - config
- type: directory
  path: src/data/authors
  label: Person
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - person
- type: document
  path: src/pages/blog/index.md
  label: Blog
  templates:
  - blog
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - landing
  - page
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_AUTH0_AUDIENCE=hasura
  - GATSBY_AUTH0_CLIENT_ID=9KoW2iyJAGHrdlDzcKewzQ9QZwltqrqL
  - GATSBY_AUTH0_DOMAIN=radimal.us.auth0.com
  - GATSBY_HASURA_API_URL=http://hasuragraphqlapi-loadbalancer-290405511.us-east-1.elb.amazonaws.com/v1/graphql
  - GATSBY_HASURA_GRAPHQL_ADMIN_SECRET=R$qalt22345678
  preview_output_directory: "/"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  instant_preview_command: yarn run develop
