---
label: Action
hide_body: true
display_field: label
fields:
- type: text
  name: label
  label: Label
  config:
    required: true
- type: text
  name: url
  label: URL
  config:
    required: true
- type: select
  name: style
  label: Style
  default: link
  config:
    source:
      type: custom
    options:
    - link
    - primary
    - secondary
- type: boolean
  name: has_icon
  label: Show icon
  default: false
- type: select
  name: icon
  label: Icon
  config:
    source:
      type: custom
    options:
    - arrow-left
    - arrow-right
    - envelope
    - facebook
    - github
    - instagram
    - linkedin
    - twitter
    - vimeo
    - youtube
- type: select
  name: icon_position
  label: Icon position
  description: The position of the icon relative to text
  default: left
  config:
    source:
      type: custom
    options:
    - left
    - right
- type: boolean
  name: new_window
  label: Open in new window
  description: Should the link open a new tab
  default: false
- type: boolean
  name: no_follow
  label: No follow
  description: Add rel="nofollow" attribute to the link
  default: false
- type: text
  name: type
  label: Object Type
  description: The type of the object
  hidden: true
  default: action
  config:
    required: true
